[[redirects]]
from="/*"
to = "/education.html"
status=200

# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[build]
  command = "npm run build"
  publish = "dist"
  node_version = "14"  # Adjust this based on your project requirements
